# Generated by Django 6.1.1 on 2026-09-08 03:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DiagramClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('position_x', models.FloatField(default=0)),
                ('position_y', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('diagram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='diagrams.diagram')),
            ],
        ),
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('data_type', models.CharField(choices=[('INTEGER', 'Integer'), ('BIGINT', 'BigInt'), ('VARCHAR', 'Varchar'), ('TEXT', 'Text'), ('BOOLEAN', 'Boolean'), ('DATE', 'Date'), ('DATETIME', 'DateTime'), ('DECIMAL', 'Decimal'), ('FLOAT', 'Float'), ('UUID', 'UUID')], max_length=30)),
                ('length', models.PositiveIntegerField(blank=True, null=True)),
                ('is_primary_key', models.BooleanField(default=False)),
                ('is_nullable', models.BooleanField(default=True)),
                ('is_unique', models.BooleanField(default=False)),
                ('default_value', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('diagram_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='diagrams.diagramclass')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collaborators', models.ManyToManyField(blank=True, related_name='collaborative_projects', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='diagram',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagrams', to='diagrams.project'),
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('ONE_TO_ONE', '1:1'), ('ONE_TO_MANY', '1:N'), ('MANY_TO_ONE', 'N:1'), ('MANY_TO_MANY', 'N:M')], max_length=30)),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('diagram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships', to='diagrams.diagram')),
                ('source_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relationships', to='diagrams.diagramclass')),
                ('target_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relationships', to='diagrams.diagramclass')),
            ],
        ),
    ]
