# Generated by Django 6.1.1 on 2026-09-22 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagrams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationship',
            name='source_handle',
            field=models.CharField(default='right', max_length=10),
        ),
        migrations.AddField(
            model_name='relationship',
            name='target_handle',
            field=models.CharField(default='left', max_length=10),
        ),
    ]
